version: '3'
services:
  mongodb:
    image: "mongo"
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db
  backend:
    image: ${DOCKER_REGISTRY}/odts-backend-repo
    build:
      context: ./backend/
      dockerfile: Dockerfile-Backend
    ports:
      - "4001:4001"
    depends_on:
      - mongodb
  frontend:
    image: ${DOCKER_REGISTRY}/odts-frontend-repo
    build:
      context: .
      dockerfile: Dockerfile-Frontend
    ports:
      - "3000:3000"
    command: 'npm start'
    depends_on:
      - backend
volumes:
  mongodata: