version: '3'
services:
  mongodb:
    image: "mongo"
    ports:
      - "27017:27017"
#    environment:
#      - MONGO_INITDB_ROOT_USERNAME=cs218
#      - MONGO_INITDB_ROOT_PASSWORD=cs218
    restart: on-failure
  backend:
    build:
      context: ./backend/
      dockerfile: Dockerfile-Backend
    ports:
      - "4001:4001"
    volumes:
      - ./backend:/usr/src/app
    depends_on:
      - mongodb
  frontend:
    build:
      context: .
      dockerfile: Dockerfile-Frontend
    ports:
      - "3000:3000"
    command: 'npm start'
    depends_on:
      - backend